---
abstract: 'shortcuts for writing Tickit apps'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Capture::Tiny: 0
  Test::CheckDeps: 0.006
  Test::Fatal: 0.010
  Test::More: 0.98
  Test::Refcount: 0.07
  blib: 0
  perl: 5.010001
configure_requires:
  ExtUtils::MakeMaker: 6.48
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-DSL
requires:
  Future: 0.15
  List::UtilsBy: 0
  Mixin::Event::Dispatch: 1.000
  Tickit: 0.37
  Tickit::Widget::Menu: 0.05
  Tickit::Widget::Progressbar: 0.002
  Tickit::Widget::ScrollBox: 0.01
  Tickit::Widget::Scroller: 0.12
  Tickit::Widget::SegmentDisplay: 0.01
  Tickit::Widget::SparkLine: 0.001
  Tickit::Widget::Statusbar: 0.001
  Tickit::Widget::Tabbed: 0.010
  Tickit::Widget::Table: 0.100
  Tickit::Widget::Tree: 0.002
  Tickit::Widgets: 0.12
  Try::Tiny: 0
  curry: 0
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Tickit-DSL
  homepage: http://search.cpan.org/dist/Tickit-DSL/
version: 0.002
